// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

type Base struct {
	Name string `json:"name"`
}

type Savegame struct {
	Bases    []*Base    `json:"bases"`
	Soldiers []*Soldier `json:"soldiers"`
}

type Soldier struct {
	Slot     int    `json:"slot"`
	Rank     string `json:"rank"`
	Name     string `json:"name"`
	Missions int    `json:"missions"`
	Kills    int    `json:"kills"`
}
