package geoscape_test

import (
	"encoding/binary"
	"testing"

	"github.com/go-restruct/restruct"
	"github.com/redtoad/xcom-editor/internal/geoscape"
	"github.com/stretchr/testify/assert"
)

func TestAlienFile_Unpack(t *testing.T) {
	buf := MustLoadFromBase64(testFile_ALIEN_DAT)
	var f geoscape.AlienFile
	err := restruct.Unpack(buf, binary.LittleEndian, &f)
	assert.NoError(t, err)
	assert.Equal(t, 12, len(f.Months))

	// Month 0 (current month)
	m0 := f.Months[0]
	assert.Equal(t, int32(2), m0.USA)
	assert.Equal(t, int32(25), m0.Russia)
	assert.Equal(t, int32(15), m0.UK)
	assert.Equal(t, int32(5), m0.France)
	assert.Equal(t, int32(38), m0.Brazil)
	assert.Equal(t, int32(3), m0.NorthAmerica)
	assert.Equal(t, int32(1), m0.Arctic)
	assert.Equal(t, int32(2), m0.Antarctica)
	assert.Equal(t, int32(195), m0.SouthAmerica)

	// Month 11 (oldest, should be zero for a new game)
	m11 := f.Months[11]
	assert.Equal(t, int32(0), m11.USA)
	assert.Equal(t, int32(0), m11.Europe)
}

func TestAlienFile_RoundTrip(t *testing.T) {
	buf := MustLoadFromBase64(testFile_ALIEN_DAT)

	var f geoscape.AlienFile
	if err := restruct.Unpack(buf, binary.LittleEndian, &f); err != nil {
		t.Fatalf("could not unpack AlienFile: %v", err)
	}

	packed, err := restruct.Pack(binary.LittleEndian, &f)
	if err != nil {
		t.Fatalf("could not pack AlienFile: %v", err)
	}

	if len(buf) != len(packed) {
		t.Fatalf("size mismatch: original=%d packed=%d", len(buf), len(packed))
	}

	for i := range buf {
		if buf[i] != packed[i] {
			t.Errorf("byte mismatch at offset %d: original=0x%02x packed=0x%02x", i, buf[i], packed[i])
		}
	}
}

// base64 -i GAME/GAME_1/ALIEN.DAT -b 120 | pbcopy
const testFile_ALIEN_DAT = `
AgAAABkAAAAPAAAABQAAAAIAAAABAAAAAQAAAAEAAAAAAAAAAAAAACYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAABAAAAAgAAAMMAAABkAAAABwAAAAEA
AAACAAAAAAAAAAEAAAAAAAAACQAAAAcAAAABAAAAAAAAAAAAAAAHAAAABwAAAAEAAAAAAAAAAQAAAAMAAAAAAAAAAAAAAAEAAADzAwAASQQAAAAAAAAAAAAA
AAAAAAAAAAABAAAAAwAAAAYAAAD3AwAAGgAAAAUAAAAHAAAAAwAAAAMAAAABAAAAuwQAAAQAAAACAAAAAQAAAAgAAAADAAAAhwAAAAQAAAACAAAAAAAAAAIA
AAAAAAAABgAAAAAAAAACAAAAAAAAAAIAAAABAAAAAAAAAAIAAAABAAAABQAAAAQAAAACAAAAAAAAABUAAAA0AAAAAgAAAAwAAAAHAAAAfAAAAAUAAAAEAAAA
AQAAAAAAAAACAAAABQAAABEAAAAAAAAAAQAAAAEAAAABAAAAAQAAAAEAAAAAAAAAAgAAAAAAAAABAAAABAAAAAAAAAAGAAAABgAAABIAAAACAAAAAAAAAAAA
AABPAAAA+wAAAAAAAAAGAAAAAQAAAAwAAAADAAAABgAAAAgAAAAAAAAACAAAAAAAAAAJAAAABQAAAAIAAAAEAAAABQAAAE4AAAAAAAAAAAAAAAIAAAAEAAAA
AQAAAAIAAABqAAAAAQAAAAIAAAACAAAAAwAAAAUAAAAHAAAAmAAAAGwAAAC2AAAAAwAAAAAAAAAAAAAAAQAAAAQAAAAFAAAABAAAAAUAAAADAAAABAAAAAIA
AAADAAAABAAAAAAAAAAAAAAAAQAAAAAAAAADAAAAAQAAADAAAAAHAAAAAQAAAAIAAAAAAAAABQAAAAIAAAAEAAAAAgAAAG0AAABsAAAABgAAAAcAAAAJAAAA
AQAAAOcAAAACAAAAAwAAAAIAAAAJAAAABQAAAHcAAAADAAAAAAAAAAIAAAAAAAAAAAAAAAUAAAABAAAAOwAAAAEAAABrAAAALgEAAAEAAAA3AAAAAQAAAAcA
AAAHAAAABgAAAAYAAAAXAAAAUQIAAAUAAAD3AAAADAAAAAcAAADTAAAABQAAAAYAAAAHAAAACgAAAAcAAADbAAAAHAAAAAcAAAACAAAAAgAAAAEAAAAJAAAA
AAAAAAMAAAABAAAAAwAAAAcAAAABAAAAAQAAAAEAAAAKAAAABwAAAAQAAAAGAAAAkwAAAMEAAAAHAAAACgAAAAsAAADVAAAABAAAAAIAAAAEAAAABwAAAAcA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA`
