// Code generated by "stringer -type=Facility,Inventory -output=base_dat_string.go -linecomment -trimprefix Inventory"; DO NOT EDIT.

package geoscape

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccessLift-0]
	_ = x[LivingQuarters-1]
	_ = x[Laboratory-2]
	_ = x[Workshop-3]
	_ = x[SmallRadarSystem-4]
	_ = x[LargeRadarSystem-5]
	_ = x[MissileDefense-6]
	_ = x[GeneralStores-7]
	_ = x[AlienContainment-8]
	_ = x[LaserDefense-9]
	_ = x[PlasmaDefense-10]
	_ = x[FusionBallDefense-11]
	_ = x[GravShield-12]
	_ = x[MindShield-13]
	_ = x[PsionicLaboratory-14]
	_ = x[HyperwaveDecoder-15]
	_ = x[HangarTopLeft-16]
	_ = x[HangarTopRight-17]
	_ = x[HangarBottomLeft-18]
	_ = x[HangarBottomRight-19]
	_ = x[Empty-255]
}

const (
	_Facility_name_0 = "Access LiftLiving QuartersLaboratoryWorkshopSmall Radar SystemLarge Radar SystemMissile DefenseGeneral StoresAlien ContainmentLaser DefensePlasma DefenseFusion Ball DefenseGrav ShieldMind ShieldPsionic laboratoryHyperwave DecoderHangar (top left)Hangar (top right)Hangar (bottom left)Hangar (bottom right)"
	_Facility_name_1 = "Empty"
)

var (
	_Facility_index_0 = [...]uint16{0, 11, 26, 36, 44, 62, 80, 95, 109, 126, 139, 153, 172, 183, 194, 212, 229, 246, 264, 284, 305}
)

func (i Facility) String() string {
	switch {
	case i <= 19:
		return _Facility_name_0[_Facility_index_0[i]:_Facility_index_0[i+1]]
	case i == 255:
		return _Facility_name_1
	default:
		return "Facility(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InventoryStingrayLauncher-0]
	_ = x[InventoryAvalancheLauncher-1]
	_ = x[InventoryCannon-2]
	_ = x[InventoryFusionBallLauncher-3]
	_ = x[InventoryLaserCannon-4]
	_ = x[InventoryPlasmaBeam-5]
	_ = x[InventoryStingrayMissile-6]
	_ = x[InventoryAvalancheMissile-7]
	_ = x[InventoryCannonRounds-8]
	_ = x[InventoryFusionBalls-9]
	_ = x[InventoryTankCannon-10]
	_ = x[InventoryTankRocketLauncher-11]
	_ = x[InventoryTankLaserCannon-12]
	_ = x[InventoryHovertankPlasma-13]
	_ = x[InventoryHovertankLauncher-14]
	_ = x[InventoryPistol-15]
	_ = x[InventoryPistolClip-16]
	_ = x[InventoryRifle-17]
	_ = x[InventoryRifleClip-18]
	_ = x[InventoryHeavyCannon-19]
	_ = x[InventoryHCAPAmmo-20]
	_ = x[InventoryHCHEAmmo-21]
	_ = x[InventoryHCINAmmo-22]
	_ = x[InventoryAutoCannon-23]
	_ = x[InventoryACAPAmmo-24]
	_ = x[InventoryACHEAmmo-25]
	_ = x[InventoryACINAmmo-26]
	_ = x[InventoryRocketLauncher-27]
	_ = x[InventorySmallRocket-28]
	_ = x[InventoryLargeRocket-29]
	_ = x[InventoryIncendiaryRocket-30]
	_ = x[InventoryLaserPistol-31]
	_ = x[InventoryLaserRifle-32]
	_ = x[InventoryHeavyLaser-33]
	_ = x[InventoryGrenade-34]
	_ = x[InventorySmokeGrenade-35]
	_ = x[InventoryProximityGrenade-36]
	_ = x[InventoryHighExplosive-37]
	_ = x[InventoryMotionScanner-38]
	_ = x[InventoryMediKit-39]
	_ = x[InventoryPsiAmp-40]
	_ = x[InventoryStunRod-41]
	_ = x[InventoryElectroFlare-42]
	_ = x[InventoryCorpse-46]
	_ = x[InventoryCorpseArmour-47]
	_ = x[InventoryCorpsePowersuit-48]
	_ = x[InventoryHeavyPlasma-49]
	_ = x[InventoryHeavyPlasmaClip-50]
	_ = x[InventoryPlasmaRifle-51]
	_ = x[InventoryPlasmaRifleClip-52]
	_ = x[InventoryPlasmaPistol-53]
	_ = x[InventoryPlasmaPistolClip-54]
	_ = x[InventoryBlasterLauncher-55]
	_ = x[InventoryBlasterBomb-56]
	_ = x[InventorySmallLauncher-57]
	_ = x[InventoryStunBomb-58]
	_ = x[InventoryAlienGrenade-59]
	_ = x[InventoryElerium115-60]
	_ = x[InventoryMindProbe-61]
	_ = x[InventorySectoidCorpse-65]
	_ = x[InventorySnakemanCorpse-66]
	_ = x[InventoryEtherealCorpse-67]
	_ = x[InventoryMutonCorpse-68]
	_ = x[InventoryFloaterCorpse-69]
	_ = x[InventoryCelatidCorpse-70]
	_ = x[InventorySilacoidCorpse-71]
	_ = x[InventoryChryssalidCorpse-72]
	_ = x[InventoryReaperCorpse-73]
	_ = x[InventorySectopodCorpse-74]
	_ = x[InventoryCyberdiscCorpse-75]
	_ = x[InventoryHovertankCorpse-76]
	_ = x[InventoryTankCorpse-77]
	_ = x[InventoryMaleCivilianCorpse-78]
	_ = x[InventoryFemaleCivilianCorpse-79]
	_ = x[InventoryUFOPowerSource-80]
	_ = x[InventoryUFONavigation-81]
	_ = x[InventoryUFOConstruction-82]
	_ = x[InventoryAlienFood-83]
	_ = x[InventoryAlienReproduction-84]
	_ = x[InventoryAlienEntertainment-85]
	_ = x[InventoryAlienSurgery-86]
	_ = x[InventoryExaminationRoom-87]
	_ = x[InventoryAlienAlloys-88]
	_ = x[InventoryAlienHabitat-89]
	_ = x[InventoryPersonalArmour-90]
	_ = x[InventoryPowerSuit-91]
	_ = x[InventoryFlyingSuit-92]
	_ = x[InventoryHWPCannonShell-93]
	_ = x[InventoryHWPRockets-94]
	_ = x[InventoryHWPFusionBomb-95]
}

const (
	_Inventory_name_0 = "stingray launcheravalanche launcherCannonFusionBallLauncherLaserCannonPlasmaBeamStingrayMissileAvalancheMissileCannonRoundsFusionBallsTankCannonTankRocketLauncherTankLaserCannonHovertankPlasmaHovertankLauncherPistolPistolClipRifleRifleClipHeavyCannonHCAPAmmoHCHEAmmoHCINAmmoAutoCannonACAPAmmoACHEAmmoACINAmmoRocketLauncherSmallRocketLargeRocketIncendiaryRocketLaserPistolLaserRifleHeavyLaserGrenadeSmokeGrenadeProximityGrenadeHighExplosiveMotionScannerMediKitPsiAmpStunRodElectroFlare"
	_Inventory_name_1 = "CorpseCorpseArmourCorpsePowersuitHeavyPlasmaHeavyPlasmaClipPlasmaRiflePlasmaRifleClipPlasmaPistolPlasmaPistolClipBlasterLauncherBlasterBombSmallLauncherStunBombAlienGrenadeElerium115MindProbe"
	_Inventory_name_2 = "SectoidCorpseSnakemanCorpseEtherealCorpseMutonCorpseFloaterCorpseCelatidCorpseSilacoidCorpseChryssalidCorpseReaperCorpseSectopodCorpseCyberdiscCorpseHovertankCorpseTankCorpseMaleCivilianCorpseFemaleCivilianCorpseUFOPowerSourceUFONavigationUFOConstructionAlienFoodAlienReproductionAlienEntertainmentAlienSurgeryExaminationRoomAlienAlloysAlienHabitatPersonalArmourPowerSuitFlyingSuitHWPCannonShellHWPRocketsHWPFusionBomb"
)

var (
	_Inventory_index_0 = [...]uint16{0, 17, 35, 41, 59, 70, 80, 95, 111, 123, 134, 144, 162, 177, 192, 209, 215, 225, 230, 239, 250, 258, 266, 274, 284, 292, 300, 308, 322, 333, 344, 360, 371, 381, 391, 398, 410, 426, 439, 452, 459, 465, 472, 484}
	_Inventory_index_1 = [...]uint8{0, 6, 18, 33, 44, 59, 70, 85, 97, 113, 128, 139, 152, 160, 172, 182, 191}
	_Inventory_index_2 = [...]uint16{0, 13, 27, 41, 52, 65, 78, 92, 108, 120, 134, 149, 164, 174, 192, 212, 226, 239, 254, 263, 280, 298, 310, 325, 336, 348, 362, 371, 381, 395, 405, 418}
)

func (i Inventory) String() string {
	switch {
	case 0 <= i && i <= 42:
		return _Inventory_name_0[_Inventory_index_0[i]:_Inventory_index_0[i+1]]
	case 46 <= i && i <= 61:
		i -= 46
		return _Inventory_name_1[_Inventory_index_1[i]:_Inventory_index_1[i+1]]
	case 65 <= i && i <= 95:
		i -= 65
		return _Inventory_name_2[_Inventory_index_2[i]:_Inventory_index_2[i+1]]
	default:
		return "Inventory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
