// Code generated by "stringer -type=CraftType,Altitude,FlightMode,WeaponType,MissionType,MissionZone,CraftStatus -output=craft_dat_string.go -linecomment"; DO NOT EDIT.

package geoscape

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Skyranger-0]
	_ = x[Lightning-1]
	_ = x[Avenger-2]
	_ = x[Interceptor-3]
	_ = x[Firestorm-4]
	_ = x[SmallScout-5]
	_ = x[MediumScout-6]
	_ = x[LargeScout-7]
	_ = x[Harvester-8]
	_ = x[Abductor-9]
	_ = x[TerrorShip-10]
	_ = x[Battleship-11]
	_ = x[SupplyShip-12]
}

const _CraftType_name = "SkyrangerLightningAvengerInterceptorFirestormsmall scoutmedium scoutlarge scoutHarvesterAbductorterror shipBattleshipsupply ship"

var _CraftType_index = [...]uint8{0, 9, 18, 25, 36, 45, 56, 68, 79, 88, 96, 107, 117, 128}

func (i CraftType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CraftType_index)-1 {
		return "CraftType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CraftType_name[_CraftType_index[idx]:_CraftType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ground-0]
	_ = x[VeryLow-1]
	_ = x[Low-2]
	_ = x[High-3]
	_ = x[VeryHigh-4]
}

const _Altitude_name = "Groundvery lowLowHighvery high"

var _Altitude_index = [...]uint8{0, 6, 14, 17, 21, 30}

func (i Altitude) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Altitude_index)-1 {
		return "Altitude(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Altitude_name[_Altitude_index[idx]:_Altitude_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoDestination-0]
	_ = x[SingleDestination-1]
	_ = x[MultipleDestinations-2]
}

const _FlightMode_name = "No destination set (at base)Single destinationMultiple destinations (UFO only)"

var _FlightMode_index = [...]uint8{0, 28, 46, 78}

func (i FlightMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_FlightMode_index)-1 {
		return "FlightMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FlightMode_name[_FlightMode_index[idx]:_FlightMode_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Stingray-0]
	_ = x[Avalanche-1]
	_ = x[Cannon-2]
	_ = x[FusionBall-3]
	_ = x[LaserCannon-4]
	_ = x[PlasmaBeam-5]
}

const _WeaponType_name = "StingrayAvalancheCannonfusion balllaser cannonplasma beam"

var _WeaponType_index = [...]uint8{0, 8, 17, 23, 34, 46, 57}

func (i WeaponType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_WeaponType_index)-1 {
		return "WeaponType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WeaponType_name[_WeaponType_index[idx]:_WeaponType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MissionAlienResearch-0]
	_ = x[MissionAlienHarvest-1]
	_ = x[MissionAlienAbduction-2]
	_ = x[MissionAlienInfiltration-3]
	_ = x[MissionAlienBase-4]
	_ = x[MissionAlienTerror-5]
	_ = x[MissionAlienRetaliation-6]
	_ = x[MissionAlienSupply-7]
}

const _MissionType_name = "Alien ResearchAlien HarvestAlien AbductionAlien InfiltrationAlien BaseAlien TerrorAlien RetaliationAlien Supply"

var _MissionType_index = [...]uint8{0, 14, 27, 42, 60, 70, 82, 99, 111}

func (i MissionType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MissionType_index)-1 {
		return "MissionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MissionType_name[_MissionType_index[idx]:_MissionType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NorthAmerica-0]
	_ = x[Arctic-1]
	_ = x[Antarctica-2]
	_ = x[SouthAmerica-3]
	_ = x[Europe-4]
	_ = x[NorthAfrica-5]
	_ = x[SouthernAfrica-6]
	_ = x[CentralAsia-7]
	_ = x[SouthEastAsia-8]
	_ = x[Siberia-9]
	_ = x[Australasia-10]
	_ = x[Pacific-11]
	_ = x[NorthAtlantic-12]
	_ = x[SouthAtlantic-13]
	_ = x[IndianOcean-14]
}

const _MissionZone_name = "North AmericaArcticAntarcticaSouth AmericaEuropeNorth AfricaSouthern AfricaCentral AsiaSouth East AsiaSiberiaAustralasiaPacificNorth Atlantic (unused)South Atlantic (unused)Indian Ocean (unused)"

var _MissionZone_index = [...]uint8{0, 13, 19, 29, 42, 48, 60, 75, 87, 102, 109, 120, 127, 150, 173, 194}

func (i MissionZone) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MissionZone_index)-1 {
		return "MissionZone(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MissionZone_name[_MissionZone_index[idx]:_MissionZone_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ready-0]
	_ = x[Out-1]
	_ = x[Repairs-2]
	_ = x[Refueling-3]
	_ = x[Rearming-4]
}

const _CraftStatus_name = "ReadyOutRepairsRefuelingRearming"

var _CraftStatus_index = [...]uint8{0, 5, 8, 15, 24, 32}

func (i CraftStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CraftStatus_index)-1 {
		return "CraftStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CraftStatus_name[_CraftStatus_index[idx]:_CraftStatus_index[idx+1]]
}
