// Code generated by "stringer -type=LocationType -output=loc_dat_string.go -linecomment"; DO NOT EDIT.

package geoscape

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unused-0]
	_ = x[AlienShip-1]
	_ = x[XCOMShip-2]
	_ = x[XCOMBase-3]
	_ = x[AlienBase-4]
	_ = x[CrashSite-5]
	_ = x[LandedUFO-6]
	_ = x[Waypoint-7]
	_ = x[TerrorSite-8]
}

const _LocationType_name = "UnusedAlien ShipX-COM ShipX-COM BaseAlien BaseCrash SiteLanded UFOWaypointTerrorSite"

var _LocationType_index = [...]uint8{0, 6, 16, 26, 36, 46, 56, 66, 74, 84}

func (i LocationType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LocationType_index)-1 {
		return "LocationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LocationType_name[_LocationType_index[idx]:_LocationType_index[idx+1]]
}
