// Code generated by "stringer -type=Rank,Armor,Gender,Appearance -output=soldier_dat_string.go -linecomment"; DO NOT EDIT.

package geoscape

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Rookie-0]
	_ = x[Squaddie-1]
	_ = x[Sergeant-2]
	_ = x[Captain-3]
	_ = x[Colonel-4]
	_ = x[Commander-5]
	_ = x[DeadOrUnused - -1]
}

const _Rank_name = "Dead or UnusedRookieSquaddieSergeantCaptainColonelCommander"

var _Rank_index = [...]uint8{0, 14, 20, 28, 36, 43, 50, 59}

func (i Rank) String() string {
	idx := int(i) - -1
	if i < -1 || idx >= len(_Rank_index)-1 {
		return "Rank(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Rank_name[_Rank_index[idx]:_Rank_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoArmor-0]
	_ = x[PersonalArmour-1]
	_ = x[PowerSuit-2]
	_ = x[FlyingSuit-3]
	_ = x[SectoidArmor-4]
	_ = x[SnakemanArmor-5]
	_ = x[EtherealArmor-6]
	_ = x[MutonArmor-7]
	_ = x[FloaterArmor-8]
	_ = x[CelatidArmor-9]
	_ = x[SilacoidArmor-10]
	_ = x[ChryssalidArmor-11]
}

const _Armor_name = "NoArmorPersonal ArmourPower SuitFlying SuitSectoid ArmourSnakeman ArmourEthereal ArmourMuton ArmourFloater ArmourCelatid ArmourSilacoid ArmourChryssalid Armour"

var _Armor_index = [...]uint8{0, 7, 22, 32, 43, 57, 72, 87, 99, 113, 127, 142, 159}

func (i Armor) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Armor_index)-1 {
		return "Armor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Armor_name[_Armor_index[idx]:_Armor_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Male-0]
	_ = x[Female-1]
}

const _Gender_name = "MaleFemale"

var _Gender_index = [...]uint8{0, 4, 10}

func (i Gender) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Gender_index)-1 {
		return "Gender(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Gender_name[_Gender_index[idx]:_Gender_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Blonde-0]
	_ = x[BrownHair-1]
	_ = x[Oriental-2]
	_ = x[African-3]
}

const _Appearance_name = "BlondeBrown HairOrientalAfrican"

var _Appearance_index = [...]uint8{0, 6, 16, 24, 31}

func (i Appearance) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Appearance_index)-1 {
		return "Appearance(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Appearance_name[_Appearance_index[idx]:_Appearance_index[idx+1]]
}
