// This program generates resources_list.go. It can be invoked by running
// go generate ./...

//go:build ignore

package main

import (
	"bytes"
	"encoding/csv"
	"go/format"
	"io"
	"log"
	"os"
	"strconv"
	"text/template"
)

const resourceFiles = "resource_files.csv"

type csvRow struct {
	Path          string
	Valid         bool
	Format        string
	PaletteNr     int
	Width, Height int
	TabFile       string
	TabOffset     int
	Comment       string
}

func toInt(txt string, defaultValue int) int {
	if value, err := strconv.Atoi(txt); txt != "" && err == nil {
		return value
	}
	return defaultValue
}

func main() {

	csvFile, err := os.Open(resourceFiles)
	if err != nil {
		log.Fatalln("Couldn't open the csv file:", err)
	}

	// Parse the file
	buf := csv.NewReader(csvFile)
	buf.Comma = ';'
	buf.Comment = '#'

	// skip header
	_, err = buf.Read()
	if err != nil {
		dieOnError(err)
	}

	var rows []*csvRow

	formats := map[string]string{
		"SCR": "ImageFormatSCR",
		"SPK": "ImageFormatSPK",
		"PCK": "ImageFormatPCK",
	}

	// Iterate through the records
	for {
		// Read each record from csv
		record, err := buf.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			log.Fatal(err)
		}
		row := &csvRow{
			Path:      record[0],
			Format:    formats[record[1]],
			PaletteNr: toInt(record[2], -1),
			Width:     toInt(record[3], -1),
			Height:    toInt(record[4], -1),
			TabFile:   record[5],
			TabOffset: toInt(record[6], -1),
			Comment:   record[7],
		}
		row.Valid = row.PaletteNr != -1
		if row.Path != "" {
			rows = append(rows, row)
		}
	}

	var tpl bytes.Buffer
	err = packageTemplate.Execute(&tpl, struct {
		Input string
		Rows  []*csvRow
	}{
		Input: resourceFiles,
		Rows:  rows,
	})
	dieOnError(err)

	// format code with go fmt before saving to file
	content, err := format.Source(tpl.Bytes())
	dieOnError(err)

	f, err := os.Create("resource_list.go")
	dieOnError(err)
	defer f.Close()

	_, err = f.Write(content)
	dieOnError(err)

}

func dieOnError(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
// This file was generated automatically based on {{ .Input }}

package resources

var Images = map[string]ImageEntry{
{{- range .Rows }}
	{{- if .Valid }}
	{{ printf "%q" .Path }}: { {{- .Format }}, {{ .PaletteNr }}, {{ .Width }}, {{ .Height }}, {{ printf "%q" .TabFile }}, {{ .TabOffset -}} },
	{{- if .Comment}} // {{ .Comment }}
	{{- end }}
	{{- else }}
	// {{ .Path }}
	{{- end }}
{{- end }}
}
`))
