// Code generated by "stringer -type=Rank -output=soldiers_string.go -linecomment"; DO NOT EDIT.

package savegame

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Rookie-0]
	_ = x[Squaddie-1]
	_ = x[Sergeant-2]
	_ = x[Captain-3]
	_ = x[Colonel-4]
	_ = x[Commander-5]
}

const _Rank_name = "RookieSquaddieSergeantCaptainColonelCommander"

var _Rank_index = [...]uint8{0, 6, 14, 22, 29, 36, 45}

func (i Rank) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Rank_index)-1 {
		return "Rank(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Rank_name[_Rank_index[idx]:_Rank_index[idx+1]]
}
